### ISSUE TITLE
sub_type is not supported

### ISSUE THREAD

**Issue by tuxpeople** [brennerm/uptimerobot-operator#28]
Hi

Thanks a lot for this useful tool!

I tried to add a monitor for a `Port`:

```
---
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: UptimeRobotMonitor
metadata:
  name: MYNAME
  namespace: MYNAME
spec:
  friendlyName: "K8S MYNAME"
  url: "MYHOSTNAME"
  type: PORT
  sub_type: "Custom Port"
  port: 22
  interval: 300
```

This gives me the following error (I'm using Flux v2):

```
error validating data: ValidationError(UptimeRobotMonitor.spec): unknown field "sub_type" in io.github.brennerm.uroperator.v
1beta1.UptimeRobotMonitor.spec;
```

If I remove `sub_type` it passes validation but gets rejected by the UptimeRobot API:

```
[2021-06-03 09:42:24,986] kopf.objects         [ERROR   ] [MYNAME/MYNAME] Handler 'on_create' failed permanently: failed to create monitor: {'type': 'missing_parameter', 'parameter_name': 'sub_type', 'message': 'sub_type parameter │
│  is missing.'}
```

According to the API Documentation, `sub_type` is normally optional, but required for port monitoring.

I use version 0.3.0.
