### ISSUE TITLE
Unable to create monitor with Basic Auth

### ISSUE THREAD

**Issue by hdp-sami** [brennerm/uptimerobot-operator#30]
Hi there,

I've been trying to create a new Uptime monitor using the following YAML but I'm getting a validation error stating that the `httpAuthSecret` field is unknown. 

My YAML:
```
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: UptimeRobotMonitor
metadata:
  name: my-application-monitor
  namespace: public
spec:
  url: "https://exampledomain.com"
  type: HTTPS
  interval: 300
  friendlyName: "My Application Monitor"
  alertContacts: "1234_0_0"
  httpAuthType: BASIC_AUTH
  httpAuthSecret: auth-secret
```

My create command and error:
```
$ k create -f uptime-monitor-crd.yaml
error: error validating "uptime-monitor-crd.yaml": error validating data: ValidationError(UptimeRobotMonitor.spec): unknown field "httpAuthSecret" in io.github.brennerm.uroperator.v1beta1.UptimeRobotMonitor.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

I've installed the operator using Helm by cloning the repository and doing it locally, as the steps listed in [the installation steps](https://github.com/brennerm/uptimerobot-operator#deploying-to-kubernetes-using-helm) were failing (I've added that snippet below but that's a different issue). 

```
$ helm repo add uptimerobot-operator https://brennerm.github.io/uptimerobot-operator/helm
$ helm upgrade --install uptimerobot-operator uptimerobot-operator --set uptimeRobotApiKey=1234
Release "uptimerobot-operator" does not exist. Installing it now.
Error: failed to download "uptimerobot-operator" (hint: running `helm repo update` may help)
```

Am I doing something wrong perhaps? If there's additional information I can provide to you please let me know.
